// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB60l5DsxOhKrEwt3GMhWe0VvYpSlfOMTg',
    appId: '1:409533440455:web:5615d4dbf3980c0c8279e2',
    messagingSenderId: '409533440455',
    projectId: 'wonderland-da519',
    authDomain: 'wonderland-da519.firebaseapp.com',
    storageBucket: 'wonderland-da519.appspot.com',
    measurementId: 'G-4ZEBRRFTLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBz1MtuvMcRzz3xphJki5tLAaxnyqATQo',
    appId: '1:409533440455:android:f5f7f2ab4eb5dfeb8279e2',
    messagingSenderId: '409533440455',
    projectId: 'wonderland-da519',
    storageBucket: 'wonderland-da519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs5sJKbQ902RD3ghzYdC5EeMwyWmjPCkQ',
    appId: '1:409533440455:ios:bf4b3ac1766014938279e2',
    messagingSenderId: '409533440455',
    projectId: 'wonderland-da519',
    storageBucket: 'wonderland-da519.appspot.com',
    iosClientId: '409533440455-i8p2n607hbm8v05bmo0us1ir3kudi6m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs5sJKbQ902RD3ghzYdC5EeMwyWmjPCkQ',
    appId: '1:409533440455:ios:54d73ee0db11e4e98279e2',
    messagingSenderId: '409533440455',
    projectId: 'wonderland-da519',
    storageBucket: 'wonderland-da519.appspot.com',
    iosClientId: '409533440455-jaghkp1q95ckcq6rvgtdk5isqkotbuld.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp.RunnerTests',
  );
}
